FROM python:3.10 as base

RUN mkdir app
WORKDIR /app

RUN apt-get update
RUN pip install poetry
RUN poetry config virtualenvs.create false

FROM base

COPY pyproject.toml ./
RUN poetry install

COPY main.py ./  ./
